### ISSUE TITLE
Bootstrap layout page - Incorrect link end tag

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-packages#116]
Bootstrap layout page is under /ResourcePackages/Bootstrap/MVC/Views/Layouts/default.cshtml.

@Html.StyleSheet(Url.WidgetContent("~/ResourcePackages/Bootstrap/assets/dist/css/styles.min.css"), "head")
The above codes render incorrect link end tag.
  &lt;link href="/ResourcePackages/Bootstrap/assets/dist/css/styles.min.css?package=Bootstrap" rel="stylesheet" type="text/css"&gt;&lt;/link&gt;

The correct link tag should be in this format.
  &lt;link href="/ResourcePackages/Bootstrap/assets/dist/css/styles.min.css?package=Bootstrap" rel="stylesheet" type="text/css" /&gt; (will work in HTML and XHTML)

**Comment by Boyko-Karadzhov** [comment]
Hello rlee2015,
We are aware of the issue and we already have a fix. You can expect it with the next release, v1.2.180.0.

Here is the most relevant issue: [ResourceHelper.BuildStyleSheetMarkup() generates links with closing tag - invalid markup](https://github.com/Sitefinity/feather/issues/1399)

Regards,
Boyko
