### ISSUE TITLE
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-packages#193]
After upgrades Feather MVC from 1.2.270.1 to 1.2.280.2, I can't edit/access custom page templates and pages (please see the following two error messages). I have no problems accessing custom page templates and pages in version 1.2.270.1.

1. Here are the error messages when I tried to edit one of our custom page templates.
Server Error in '/' Application.
________________________________________
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Telerik.Sitefinity.Frontend.Resources.PackageManager.GetPackageFromTemplate(PageTemplate template) +47
   Telerik.Sitefinity.Frontend.Resources.PackageManager.GetPackageFromTemplateId(String templateId) +474
   Telerik.Sitefinity.Frontend.Resources.PackageManager.GetPackageFromPageInfo() +213
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Layouts.LayoutVirtualPathBuilder.AddVariablesToPath(String layoutVirtualPath) +102
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Layouts.LayoutVirtualPathBuilder.BuildPathFromTitle(String templateTitle) +191
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Layouts.LayoutResolver.GetVirtualPath(IPageTemplate template) +166
   Telerik.Sitefinity.Modules.Pages.PageHelperImplementation.ResolveDynamicMasterPage(IPageTemplate template) +122
   Telerik.Sitefinity.Modules.Pages.TemplateDraftProxy..ctor(TemplateDraft pageData, PageDataProvider provider, Boolean isPreview, CultureInfo objectCulture, Boolean optimized) +859
   Telerik.Sitefinity.Modules.Pages.TemplateEditorRouteHandler.GetPageData(SiteMapNode node) +1388
   Telerik.Sitefinity.Web.RouteHandler.GetHttpHandler(RequestContext requestContext) +153
   System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context) +12411254
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +91
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +164

________________________________________
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249

2. Here are error messages when I tried to access one of the page (using custom page template).
Server Error in '/' Application.

Object reference not set to an instance of an object. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Telerik.Sitefinity.Frontend.Resources.PackageManager.GetPackageFromTemplate(PageTemplate template) +47
   Telerik.Sitefinity.Frontend.Resources.PackageManager.GetPackageFromNodeId(String nodeId) +628
   Telerik.Sitefinity.Frontend.Resources.PackageManager.GetPackageFromPageInfo() +814
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Layouts.LayoutVirtualPathBuilder.AddVariablesToPath(String layoutVirtualPath) +102
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Layouts.LayoutVirtualPathBuilder.BuildPathFromTitle(String templateTitle) +191
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Layouts.LayoutResolver.GetVirtualPath(IPageTemplate template) +166
   Telerik.Sitefinity.Modules.Pages.PageHelperImplementation.ResolveDynamicMasterPage(IPageTemplate template) +122
   Telerik.Sitefinity.Abstractions.VirtualPath.PageResolverBase.BuildPageTemplateRecursive(IPageTemplate pageTemplate, String theme, RequestContext context, StringBuilder output, CursorCollection placeHolders, DirectiveCollection directives, List`1 controlConatiners) +181
   Telerik.Sitefinity.Mvc.Rendering.PureMvcPageResolver.RenderPage(StringBuilder sb, PageData pageData, RequestContext context, String virtualPath) +345
   Telerik.Sitefinity.Mvc.Rendering.PureMvcPageResolver.Open(PathDefinition definition, String virtualPath) +275
   Telerik.Sitefinity.Abstractions.VirtualPath.VirtualPathManager.OpenFile(String virtualPath) +232
   System.Web.UI.TemplateParser.ParseFile(String physicalPath, VirtualPath virtualPath) +255
   System.Web.UI.TemplateParser.Parse() +12152422
   System.Web.Compilation.BaseTemplateBuildProvider.get_CodeCompilerType() +135
   System.Web.Compilation.BuildProvider.GetCompilerTypeFromBuildProvider(BuildProvider buildProvider) +189
   System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders() +265
   System.Web.Compilation.BuildProvidersCompiler.PerformBuild() +44
   System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) +580
   System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) +571
   System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) +203
   System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) +249
   System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp) +56
   Telerik.Sitefinity.Web.PageRouteHandler.InstantiateHandler(RequestContext requestContext, PageSiteNode pageDataNode, String& theme) +337
   Telerik.Sitefinity.Web.PageRouteHandler.BuildHttpHandler(RequestContext requestContext) +703
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.MvcPageRouteHandler.BuildHttpHandler(RequestContext requestContext) +11
   System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context) +12411255
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +92
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165

  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249 

Please advise, Thanks.

Richard

**Comment by mariushm** [comment]
Hi Richard,

Apologies for the inconvenience. We have localized the issue and will provide a fix shortly. 

Mariush
