### ISSUE TITLE
Foundation layout squished when MVC widget designer (Edit mode) is open

### ISSUE THREAD

**Issue by outerlooper** [Sitefinity/feather-packages#209]
The Foundation package in Feather has a problem in the backend page editor. When I click on the Edit button to open the designer for a MVC widget, the page layout (undesirably) squishes and moves to the left of the screen behind the lightbox. This does not occur in Bootstrap, so we've determined it's a bug and is happening directly out-of-box with nothing (css, js, etc) added to the SF app.

The layout is full size (1000px wide) and centered. When I click on an MVC widget Edit button to open the designer, my layout is shrunk and mangled. Sometimes it restores back to normal after saving widget edits, sometimes it doesn't. Here is a screen cap example. 
https://lh4.googleusercontent.com/-2nJ3ugZ5cIU/VcUMum7-MkI/AAAAAAAAAUE/DsDdt3whn_U/w659-h510-no/ExsqueezeMeFull.jpg

Please resolve this issue for future releases. 
How can we resolve this in the meantime?

Thank you for your help.

**Comment by Boyko-Karadzhov** [comment]
Hello @outerlooper ,

Thank you for the feedback! This should be fixed in Feather 1.3.340.0. I am closing the issue for now. Let me know if this persists after the update.

Regards,
Boyko

**Comment by outerlooper** [comment]
Thank you so much! 
Most appreciated.

Thanks,
Mike Cooper
@outerlooper
