### ISSUE TITLE
MVC forms using wrong bootstrap class

### ISSUE THREAD

**Issue by ksCookj** [Sitefinity/feather-packages#239]
Some of the form elements containers have the wrong bootstrap class:

Multiple choice, checkbox, dropdown and file upload use the class "from-group" instead of the bootstrap "form-group".

Also Paragraph form element uses class "forms-group" in Write.Default.cshtml file. Should be "form-group"

Looks like the other form elements use the correct class. I have fixed this in my project but thought you should be aware for future releases.

**Comment by RJCuthbertson** [comment]
I fixed it and issued a pull request https://github.com/Sitefinity/feather-packages/pull/240

**Comment by ElenaGaneva** [comment]
Thank you for your input! This will be included in next release of Feather.

Regards,
Elena
