### ISSUE TITLE
NPM error on "start" script in Bootstrap4 ResourcePackage

### ISSUE THREAD

**Issue by fnicollier** [Sitefinity/feather-packages#375]
Getting an "ReferenceError: Unknown plugin "transform-runtime" specified in..." when "doing npm start".
I have ran "npm install" beforehand with not errors but babel-core's "option-manager.js" throws this exception because it claims it cannot find the transform-runtime plugin.

**Comment by nikistefanov** [comment]
Hello @fnicollier 
Can you give us more information about what node and npm version you are using. Also do you have additional dependencies listed in the package.json?

**Comment by fnicollier** [comment]
Hi @nikistefanov,
I have Node V11.1.0 and npm V6.4.1.
I'm using the package.json as provided in this repo.
Thanks

**Comment by nikistefanov** [comment]
Hi @fnicollier 

Unfortunately, the current state of Bootstrap 4 package is optimized for Node.js version 8.9.4 as this was the LTS during the development of the package. We have plans to upgrade this dependency to LTS 10.13.0 in the upcoming Sitefinity patches.

Could you switch to Node.js 8.9.4 and do the same steps.

I’ve tried to reproduce your issue using your Node.js version but I didn’t get the same error. If you still have this error with Node.js 8.9.4, try manually installing the missing dependencies.

For example:
npm install babel-plugin-transform-runtime
npm install babel-preset-stage-2
npm install babel-preset-es2015

Hope this would help.

**Comment by fnicollier** [comment]
I've downgraded my Node version to 8.9.4 and still got the same error. Even after installing the additional packages.
Is it possible to add the package-lock.json to the Git repo? It is advised to commit that file.

**Comment by nikistefanov** [comment]
@fnicollier 

I’m sending you package-lock.json. Please make sure you’ve removed all node_modules and you’re using Node.js 8.9.4 before doing `npm install` and `npm start`.
[package-lock.zip](https://github.com/Sitefinity/feather-packages/files/2589624/package-lock.zip)

**Comment by fnicollier** [comment]
Thanks. Removed the node_modules, reset the package.json, added the provided package-lock.json.
Ran with Node 8.9.4 and I'm still getting the same babel-core error when the script hits the copy:js part.

**Comment by fnicollier** [comment]
Strange, I've created a new SF 11.1 project, ran npm install/start and there is worked fine as long as my cmd prompt was run as admin.
I've copied the Boostrap4 folder to replace the one I was having problems with and I there I get the problems again. May be something to do with the dept of the folders or permissions.

**Comment by fnicollier** [comment]
OK I've nailed down the problem: if my Boostrap folder is under a structure with a "src" folder, this seems to break the copy:js script. If I rename the src folder in the structure to anything else it works.

**Comment by nikistefanov** [comment]
Hi @fnicollier 
We were able to reproduces the issue. We will fix it for the next release. Thanks for the feedback.

**Comment by fnicollier** [comment]
Thank you.

**Comment by nikistefanov** [comment]
Hi @fnicollier 
Could you please verify if the issue is still relevant with the latest commit?

**Comment by fnicollier** [comment]
Hi and happy new year.

I've updated my project to SF 11.2.6900.0 and I'm happy to confirm that the Bootstrap4 resource package now builds perfectly even under a "src" folder structure.

Thank you.
