### ISSUE TITLE
Customizing the Layouts question

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather-packages#60]
Hello,

Do you know if there is a possibility to define more edit zone on the Layouts view?
I would like to hard code mandatory Zones unfortunately I can have only one @Html.SfPlaceHolder("Contentplaceholder1")

Thanks for your help.

Alex.

**Comment by mariushm** [comment]
Hi Alexander,

Currently, the only way is to drag a layout grid widget into the placeholder. We are considering to implement multiple placeholders directly in the layout files in one of the upcoming releases.

Mariush

**Comment by mariushm** [comment]
Hi Alexander,

You can now use multiple placeholders in the layout files. The improvement was just shipped with today's weekly release. I hope you'll find it useful!

Mariush
