### ISSUE TITLE
Feather-packages WCAG 2.0 Level A Issue: 3.1.1 Language of Page

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-packages#70]
Feather-packages WCAG 2.0 Level A Issue: 3.1.1 Language of Page
http://www.w3.org/TR/WCAG20/#meaning-doc-lang-id

To dynamically add a language attribute to the html tag of the page:

Here are the solution:
1.Please apply the following HTML code in \ResourcePackages\
&lt;FeatherPackage&gt;\MVC\Views\Layouts\default.cshtml.

&lt;html @Html.RenderHtmlLangAttribute()&gt;

2.To create a custom HTML helper under \ResourcePackages\HtmlHelperExtensions.cs.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SitefinityWebApp.ResourcePackages
{
public static class HtmlHelperExtensions
    {
        public static IHtmlString RenderHtmlLangAttribute(this HtmlHelper helper)
        {
            var culture = System.Threading.Thread.CurrentThread.CurrentUICulture;
            string attributeString = string.Format(@"lang=""{0}""", culture.TwoLetterISOLanguageName);
            return helper.Raw(attributeString);
        }
    }
}

**Comment by rlee2015** [comment]
Hi JenPeleva,

Will this bug be fixed soon?

Please advise, Thanks.

Richard

**Comment by mariushm** [comment]
Hi Richard,

Please accept our apologies for the delayed response, the item will be assigned shortly and will be included in next week's release.

Mariush
